name: pdf_config
description: The Flutter PDF is a library written natively in Dart for creating, reading, editing, and securing PDF files in Android, iOS, and web platforms.
version: 21.2.10
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdf

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  xml: ^6.3.0
  syncfusion_flutter_core: ^21.2.10     
  crypto: ^3.0.3
  convert: ^3.1.1

